### ISSUE TITLE
Performance is really bad on big json structures

### ISSUE THREAD

**Issue by latsson** [snappdevelopment/JsonTree#38]
Thanks for a super nice library!
I noticed some problems that hopefully is possible to solve.
I have some really big GraphQL responses to view. Sometimes it can take up to 10 seconds to load them.

Some points:
- Maybe not optimal doing Json.parseToJsonElement on the main thread.
- Don't draw non expanded elements
- Consider using a LazyColumn

**Comment by snappdevelopment** [comment]
Hi latsson,

Thank you for trying JsonTree!
You are right, the current performance is a problem. I will try to think of some improvements to make it faster.

To your suggestions:
1. That is probably a good idea. However even with doing that, the pure rendering performance is bad right now.
2. That makes sense. I will try to do that. I might need to ditch the `TreeState.EXPANDED` state, since expanding the whole tree will probably always have bad performance.
3. I also thought about doing this. I am not sure if it is possible to render a tree-like structure in a list and still be able to expand/collapse nodes. Maybe it's possible, but pretty complex. I will need to think about it for a while.

Thanks again for your feedback!
Would it be possible to provide sample data of your responses?

**Comment by snappdevelopment** [comment]
Hi @latsson 
It took a while, but I just released a snapshot version of JsonTree with improved performance.
If you want to try it you can do so by using version `2.0.0-SNAPSHOT` and adding the sonatype snapshot repository to your build. `maven { url 'https://s01.oss.sonatype.org/content/repositories/snapshots' }`

**Comment by latsson** [comment]
Nice one. I will see when I have time :)

**Comment by latsson** [comment]
Did a test now. Huge difference. Awesome work 😍

**Comment by snappdevelopment** [comment]
Thanks for testing it 👍 
I just released the stable version `2.0.0`.
I will close this issue now. Feel free to open a new issue if you encounter any problems.
